### ISSUE TITLE
check if O&M exists in ferc1 small and hydro plants tables

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/rmi-ferc1-eia#216]
Made this issue because the RMI Optimus formatted table has a field called `Total O&M Cost` that only seems to have info for steam plants (none of the wind/renewables etc.) This issue is to investigate why

**Comment by aesharpe** [comment]
Check that columns match up

**Comment by aesharpe** [comment]
Ok, so the RMI Optimus formatted table _is_ reading from the `all_plants_ferc1()` table because that table is already being used to create the `ferc1_to_eia` table which feeds into the Optimus formatted table. The issue here seems to be column alignment within the `all_plants_ferc1` table. 

The Optimus formatted table has a field called `Total O&M Cost` that is a copy off the ferc1 column `opex_nonfuel`. This column can be found in the `ferc1_steam_plants` table, but none of the other plant tables (hydro, pumped storage, small gens). 

My proposal is to calculate the `opex_nofuel` value for the other FERC tables by using the following equations:
* **small gens:** `opex_nonfuel` = `opex_total` - `opex_fuel` 
* **hydro:** `opex_nonfuel` = `opex_total`
* **pumped storage:** `opex_nonfuel` = `opex_total` 

Because neither hydro nor pumped storage units require fuel payment, it can be reasonably assumed that the nonfuel opex is equivalent to the total opex.

**Comment by aesharpe** [comment]
See #1619
