### ISSUE TITLE
enable 1-year of data processing

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/rmi-ferc1-eia#226]
In order to enable github action testing (bc everything is too beeeg).

Run through each processing step, diagnose current issues blocking 1-year processing and implement solution:
- [x] `pudl_rmi.coordinate.plant_parts_eia` (this one almost certainly already fine)
- [ ] `pudl_rmi.coordinate.deprish`: this one literally has no `year` arg's rn
- [ ] `pudl_rmi.coordinate.deprish_to_eia`: probably the main issue is in the overrides
- [ ] `pudl_rmi.coordinate.ferc1_to_eia`: I suspect we'll need to add masks for the input data (or maybe that'll be handled w/ `pudl_out`) and the training data
- [ ] `pudl_rmi.coordinate.deprish_to_ferc1`: I thiiink if everything upstream is restricted to a year this should be okay.

**Comment by katie-lamb** [comment]
Notes from check in call with Christina:
- the depreciation data: probably just need to select for a year, should be pretty easy
- the depreciation to EIA: fuzzy matching process, there is a multi year overrides table (that lives in RMI repo) that comes in and overrides the bad matches
- the ferc to eia: use `pudl_out` to filter for year, the model will perform worse but the CI will still test if the model runs
  - if the training data is improved (using the Panda spinoff) then the model will perform better again because there is more training data per year
- the ferc to depreciation: nothing needs to happen as long as the same one year is used throughout

In an ideal world we can go back to using the full plant part list (all years) when Dagster is implemented with the plant part list creation.
